[tools]
ruby   = ["4.0"]
node   = ["24"]
python = ["3.14"]
java   = ["25"]
go     = ["1.26"]
pnpm   = ["latest"]
bun = "latest"
uv = "latest"
osv-scanner = "latest"

[settings]
idiomatic_version_file = true
idiomatic_version_file_enable_tools = ["node"]
