Notion|/Applications/Notion.app|https://www.notion.so/desktop
Notion Calendar|/Applications/Notion Calendar.app|https://www.notion.so/product/calendar
Xcode|/Applications/Xcode.app|https://apps.apple.com/app/xcode/id497799835
Postgres.app|/Applications/Postgres.app|https://postgresapp.com/downloads.html
Telegram|/Applications/Telegram.app|https://telegram.org/macos
Docker Desktop|/Applications/Docker.app|https://www.docker.com/products/docker-desktop/
1Password|/Applications/1Password.app|
Claude|/Applications/Claude.app|
Firefox|/Applications/Firefox.app|
iTerm|/Applications/iTerm.app|
